package com.bac_game_server.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object representing the complete game state.
 * Server is single source of truth for letter and categories.
 */
public class GameStateDTO {
    
    @JsonProperty("sessionId")
    private String sessionId;
    
    @JsonProperty("letter")
    private String letter; // Single letter generated by server
    
    @JsonProperty("categories")
    private List<String> categories; // Synchronized by server
    
    @JsonProperty("roundDuration")
    private int roundDuration; // in seconds
    
    @JsonProperty("players")
    private List<PlayerStateDTO> players;
    
    @JsonProperty("status")
    private String status; // WAITING, IN_PROGRESS, FINISHED
    
    @JsonProperty("roundStartTime")
    private LocalDateTime roundStartTime;
    
    @JsonProperty("roundEndTime")
    private LocalDateTime roundEndTime;

    // Default constructor for Jackson
    public GameStateDTO() {
    }

    public GameStateDTO(String sessionId, String letter, List<String> categories, 
                       int roundDuration, List<PlayerStateDTO> players, String status) {
        this.sessionId = sessionId;
        this.letter = letter;
        this.categories = categories;
        this.roundDuration = roundDuration;
        this.players = players;
        this.status = status;
    }

    // Getters and Setters
    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getLetter() {
        return letter;
    }

    public void setLetter(String letter) {
        this.letter = letter;
    }

    public List<String> getCategories() {
        return categories;
    }

    public void setCategories(List<String> categories) {
        this.categories = categories;
    }

    public int getRoundDuration() {
        return roundDuration;
    }

    public void setRoundDuration(int roundDuration) {
        this.roundDuration = roundDuration;
    }

    public List<PlayerStateDTO> getPlayers() {
        return players;
    }

    public void setPlayers(List<PlayerStateDTO> players) {
        this.players = players;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getRoundStartTime() {
        return roundStartTime;
    }

    public void setRoundStartTime(LocalDateTime roundStartTime) {
        this.roundStartTime = roundStartTime;
    }

    public LocalDateTime getRoundEndTime() {
        return roundEndTime;
    }

    public void setRoundEndTime(LocalDateTime roundEndTime) {
        this.roundEndTime = roundEndTime;
    }

    @Override
    public String toString() {
        return "GameStateDTO{" +
                "sessionId='" + sessionId + '\'' +
                ", letter='" + letter + '\'' +
                ", categories=" + categories +
                ", roundDuration=" + roundDuration +
                ", players=" + players +
                ", status='" + status + '\'' +
                ", roundStartTime=" + roundStartTime +
                ", roundEndTime=" + roundEndTime +
                '}';
    }

    /**
     * Nested DTO representing a player's state within the game session.
     */
    public static class PlayerStateDTO {
        
        @JsonProperty("username")
        private String username;
        
        @JsonProperty("isHost")
        private boolean isHost;
        
        @JsonProperty("hasSubmitted")
        private boolean hasSubmitted;
        
        @JsonProperty("joinedAt")
        private LocalDateTime joinedAt;

        // Default constructor for Jackson
        public PlayerStateDTO() {
        }

        public PlayerStateDTO(String username, boolean isHost, boolean hasSubmitted, LocalDateTime joinedAt) {
            this.username = username;
            this.isHost = isHost;
            this.hasSubmitted = hasSubmitted;
            this.joinedAt = joinedAt;
        }

        public String getUsername() {
            return username;
        }

        public void setUsername(String username) {
            this.username = username;
        }

        public boolean isHost() {
            return isHost;
        }

        public void setHost(boolean host) {
            isHost = host;
        }

        public boolean isHasSubmitted() {
            return hasSubmitted;
        }

        public void setHasSubmitted(boolean hasSubmitted) {
            this.hasSubmitted = hasSubmitted;
        }

        public LocalDateTime getJoinedAt() {
            return joinedAt;
        }

        public void setJoinedAt(LocalDateTime joinedAt) {
            this.joinedAt = joinedAt;
        }

        @Override
        public String toString() {
            return "PlayerStateDTO{" +
                    "username='" + username + '\'' +
                    ", isHost=" + isHost +
                    ", hasSubmitted=" + hasSubmitted +
                    ", joinedAt=" + joinedAt +
                    '}';
        }
    }
}