package com.bac_game_server.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.*;

/**
 * JPA Entity representing a multiplayer word game session.
 * Server is single source of truth for letter, categories, and timing.
 */
@Entity
@Table(name = "game_sessions")
public class GameSessionEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "session_id", nullable = false, unique = true, length = 6)
    private String sessionId;

    @Column(name = "letter", length = 1)
    private String letter; // Single letter generated by server

    @ElementCollection
    @CollectionTable(name = "session_categories", joinColumns = @JoinColumn(name = "session_id"))
    @Column(name = "category")
    private List<String> categories = new ArrayList<>();

    @Column(name = "round_duration", nullable = false)
    private int roundDuration; // in seconds

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private GameSessionStatus status;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "round_start_time")
    private LocalDateTime roundStartTime;

    @Column(name = "round_end_time")
    private LocalDateTime roundEndTime;

    @Column(name = "host_username", nullable = false)
    private String hostUsername;

    @OneToMany(mappedBy = "gameSession", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Set<PlayerSessionEntity> playerSessions = new HashSet<>();

    // Default constructor for JPA
    protected GameSessionEntity() {
    }

    public GameSessionEntity(String sessionId, String hostUsername, List<String> categories, int roundDuration) {
        this.sessionId = sessionId;
        this.hostUsername = hostUsername;
        this.categories = new ArrayList<>(categories);
        this.roundDuration = roundDuration;
        this.status = GameSessionStatus.WAITING;
        this.createdAt = LocalDateTime.now();
    }

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
        if (status == null) {
            status = GameSessionStatus.WAITING;
        }
    }

    // Business logic methods
    public void generateLetter() {
        // Generate a random letter (server is single source of truth)
        char[] letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".toCharArray();
        Random random = new Random();
        this.letter = String.valueOf(letters[random.nextInt(letters.length)]);
    }

    public void startRound() {
        if (this.letter == null) {
            generateLetter();
        }
        this.status = GameSessionStatus.IN_PROGRESS;
        this.roundStartTime = LocalDateTime.now();
        this.roundEndTime = roundStartTime.plusSeconds(roundDuration);
    }

    public void endRound() {
        this.status = GameSessionStatus.RESULTS_PENDING;
    }

    public void finishSession() {
        this.status = GameSessionStatus.FINISHED;
    }

    public boolean canAcceptNewPlayers() {
        return status == GameSessionStatus.WAITING;
    }

    public boolean isRoundActive() {
        return status == GameSessionStatus.IN_PROGRESS && 
               roundEndTime != null && 
               LocalDateTime.now().isBefore(roundEndTime);
    }

    public int getPlayerCount() {
        return playerSessions.size();
    }

    // Helper methods for relationships
    public void addPlayerSession(PlayerSessionEntity session) {
        playerSessions.add(session);
        session.setGameSession(this);
    }

    public void removePlayerSession(PlayerSessionEntity session) {
        playerSessions.remove(session);
        session.setGameSession(null);
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getLetter() {
        return letter;
    }

    public void setLetter(String letter) {
        this.letter = letter;
    }

    public List<String> getCategories() {
        return categories;
    }

    public void setCategories(List<String> categories) {
        this.categories = categories;
    }

    public int getRoundDuration() {
        return roundDuration;
    }

    public void setRoundDuration(int roundDuration) {
        this.roundDuration = roundDuration;
    }

    public GameSessionStatus getStatus() {
        return status;
    }

    public void setStatus(GameSessionStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getRoundStartTime() {
        return roundStartTime;
    }

    public void setRoundStartTime(LocalDateTime roundStartTime) {
        this.roundStartTime = roundStartTime;
    }

    public LocalDateTime getRoundEndTime() {
        return roundEndTime;
    }

    public void setRoundEndTime(LocalDateTime roundEndTime) {
        this.roundEndTime = roundEndTime;
    }

    public String getHostUsername() {
        return hostUsername;
    }

    public void setHostUsername(String hostUsername) {
        this.hostUsername = hostUsername;
    }

    public Set<PlayerSessionEntity> getPlayerSessions() {
        return playerSessions;
    }

    public void setPlayerSessions(Set<PlayerSessionEntity> playerSessions) {
        this.playerSessions = playerSessions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GameSessionEntity that = (GameSessionEntity) o;
        return Objects.equals(id, that.id) && Objects.equals(sessionId, that.sessionId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, sessionId);
    }

    @Override
    public String toString() {
        return "GameSessionEntity{" +
                "id=" + id +
                ", sessionId='" + sessionId + '\'' +
                ", letter='" + letter + '\'' +
                ", categories=" + categories +
                ", roundDuration=" + roundDuration +
                ", status=" + status +
                ", createdAt=" + createdAt +
                ", hostUsername='" + hostUsername + '\'' +
                ", playerCount=" + getPlayerCount() +
                '}';
    }
}